# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='destination',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='destination',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
